add healthcheck http handler
thumbor/remotecv pull request #44
Opened 2022-05-02 21:06 UTC by RaphaelVRossi

Create http healthcheck endpoint for Remotecv worker.

We are running Remotecv process inside a minimal docker image, and we need to check if the process is still alive

2022-05-05 01:57 UTC, marcelometal commented on remotecv/worker.py
> +    other_group.add_argument("--with_healthcheck", default=False, type=bool, action=argparse.BooleanOptionalAction, help="Start an healthchecker http endpoint")
Replace `with_healthcheck` with `with-healthcheck`

2022-05-05 01:57 UTC, marcelometal commented on remotecv/worker.py
> +    other_group.add_argument("--server_port", default=8080, type=int, help="Server http port")
Replace `server_port` with `server-port`

2022-05-05 01:57 UTC, marcelometal commented on remotecv/worker.py
> +    other_group.add_argument("--with_healthcheck", default=False, type=bool, action=argparse.BooleanOptionalAction, help="Start an healthchecker http endpoint")
Wrap this long line ;)

2022-05-05 01:57 UTC, marcelometal commented on remotecv/worker.py
> +    other_group.add_argument("--with_healthcheck", default=False, type=bool, action=argparse.BooleanOptionalAction, help="Start an healthchecker http endpoint")
Please, add a note in README about how to use this new arg

2022-05-09 21:38 UTC, scorphus requested changes
The Python Standard Library serves so many purposes. Let's use it! We don't need yet another dependency. 🙂

2022-05-09 21:38 UTC, scorphus commented on setup.py
> +    "requests==2.*,>=2.27.1",
```suggestion
```

2022-05-09 21:38 UTC, scorphus commented on tests/test_healthcheck_handler.py
> +import requests
```suggestion
from urllib import request
```

2022-05-09 21:38 UTC, scorphus commented on tests/test_healthcheck_handler.py
> +        response = requests.get(f"http://localhost:{config.server_port}")
```suggestion
        response = request.urlopen(f"http://localhost:{config.server_port}")
```

2022-05-09 21:38 UTC, scorphus commented on tests/test_healthcheck_handler.py
> +        expect(response.text).to_equal("WORKING")
```suggestion
        expect(response.status).to_equal(200)
        expect(response.read().encode()).to_equal("WORKING")
```

2022-05-09 22:01 UTC, RaphaelVRossi commented on setup.py
> +    "requests==2.*,>=2.27.1",
Done!

2022-05-09 22:01 UTC, RaphaelVRossi commented on tests/test_healthcheck_handler.py
> +        response = requests.get(f"http://localhost:{config.server_port}")
Done!

2022-05-09 22:01 UTC, RaphaelVRossi commented on tests/test_healthcheck_handler.py
> +import requests
Done!

2022-05-09 22:01 UTC, RaphaelVRossi commented on tests/test_healthcheck_handler.py
> +        expect(response.text).to_equal("WORKING")
Done!

2022-05-10 09:04 UTC, scorphus approved these changes

2022-05-10 09:04 UTC, scorphus commented on README.md
> +If you want a healthcheck handler, you must pass a argument in remotecv
Missed that:
```suggestion
If you want a healthcheck handler, you must pass an argument in remotecv
```

2022-05-10 09:04 UTC, scorphus commented on README.md
> +port is 8080
```suggestion
port is 8080.
```
\- "Pô, Pablito. Mas tu é nitty picky, hein?"
\- 👀

2022-05-10 12:55 UTC, RaphaelVRossi commented on README.md
> +port is 8080
El Pablito não deixa passar uma.

2022-05-11 22:43 UTC, merged